# general settings
name: VD2026_tclv2.yml
model_type: MultiFrameVDModel
num_gpu: auto  # set num_gpu: 0 for cpu mode
find_unused_parameters: True
manual_seed: 0
train_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: MultiFrameVD
    type: MultiFrameVDPairedImageDataset
    dataroot_gt: ../datasets/optical/tcl/train/target
    dataroot_lq: ../datasets/optical/tcl/train/source
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: MultiFrameVD
    type: MultiFrameVDPairedImageDataset
    dataroot_gt: ../datasets/optical/tcl/test/target
    dataroot_lq: ../datasets/optical/tcl/test/source
    io_backend:
      type: disk
    batch_size: 1
    num_worker: 1

# network structures
network:
  type: MTNet

path:
  pretrain_network: ~ #experiments/base3_tclv2.yml/models/net_400000.pth
  strict_load: true
  resume_state: ~ #experiments/base3_tclv2.yml/training_states/400000.state

# training settings
train:
  ema_decay: 0.999
  optim:
    type: AdamW
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000, 100000, 100000, 100000, 100000, 100000]
    restart_weights: [1, 1, 1, 1, 1, 1]
    eta_min: !!float 5e-8

  total_iter: 600000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  # perceptual loss (content and style losses)
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv3_3': 0.5
    vgg_type: vgg16
    use_input_norm: true
    perceptual_weight: 1.0
    style_weight: 0
    range_norm: false
    criterion: l1

  # mid pixel loss
  mid_pix_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  # mid perceptual loss
  mid_perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv3_3': 0.5
    vgg_type: vgg16
    use_input_norm: true
    perceptual_weight: 0.1
    style_weight: 0
    range_norm: false
    criterion: l1

  # self-reconstruction loss
  self_recon_opt:
    type: L1Loss
    loss_weight: 0.1
    reduction: mean

  # decomposition contrastive loss
  decomp_contrastive_opt:
    type: DecompositionContrastiveLoss
    loss_weight: 0.5
    temperature: !!float 0.1
    in_batch_negative: true

# validation settings
val:
  val_freq: !!float 10000
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr_pt
      crop_border: 0
    ssim:
      type: calculate_ssim_pt
      crop_border: 0
    lpips:
      type: calculate_lpips_pt
      crop_border: 0
      better: lower

# logging settings
logger:
  print_freq: 10000
  save_checkpoint_freq: !!float 10000
  wandb:
    use_wandb: false
    project: vd2026_base
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500